AKASH ANI.md
IEDC-SJCET/Top20Coders pull request #18
Opened 2024-04-05 17:01 UTC by akash-1724

2024-04-11 16:08 UTC, rajatsandeepsen requested changes
Cool ✨ 

But can you use less # in text...

2024-04-14 19:09 UTC, alvin-dennis commented
@akash-1724 Pls work on ur '#' usage and redo it

2024-05-05 06:03 UTC, akash-1724 commented
Changed

2024-05-05 20:15 UTC, rajatsandeepsen commented on participants/AKASH ANI.md
> +# Hello! I’m Akash, a passionate Computer Science Engineering student at St. Joseph’s Engineering and Technology, Palai. I thrive on learning new skills and have a special affinity for mathematics an
Too much #

2024-05-05 20:15 UTC, rajatsandeepsen approved these changes
But cool

2024-07-17 15:19 UTC, closed without merging