Created a pull request
IEDC-SJCET/Top20Coders pull request #19
Opened 2024-04-05 18:47 UTC by AmalJoy14

2024-04-11 16:34 UTC, rajatsandeepsen requested changes
Cool ✨

2024-04-11 16:34 UTC, rajatsandeepsen commented on participants/template.md
dont delete this file

2024-04-11 16:34 UTC, rajatsandeepsen commented on participants/README.md
Rename this file to your-name-roll-no

2024-04-12 17:20 UTC, AmalJoy14 commented
Done!

2024-04-14 19:08 UTC, alvin-dennis commented
@Milansuman u can merge this after ur final recheck

2024-04-16 02:21 UTC, merged