participant file
IEDC-SJCET/Top20Coders pull request #39
Opened 2024-04-07 15:17 UTC by antresssss

2024-04-11 16:14 UTC, rajatsandeepsen requested changes
Cool 🌟 

But..
Please put the file inside "/participants"

2024-04-14 19:00 UTC, alvin-dennis commented
@Milansuman u can merge it after u do a final check

2024-04-14 19:02 UTC, alvin-dennis commented
@antresssss Also work on the formatting of the website profiles section and give ur name instead of "Full Name".

2024-04-16 02:15 UTC, Milansuman approved these changes

2024-04-16 02:15 UTC, merged